<?php 

return [
    'client_id' => env('SHOPIFY_CLIENT_ID'),
    'client_secret' => env('SHOPIFY_CLIENT_SECRET'),
    'api_version' => env('SHOPIFY_API_VERSION', '2023-07'),
    'api_scopes' => [
        //'read_all_orders', //Take approval from Shopify for the app before u can take this access scope
        'read_assigned_fulfillment_orders',
        'write_assigned_fulfillment_orders',
        'read_checkouts',
        'write_checkouts',
        'read_customers',
        'write_customers',
        'read_draft_orders',
        'write_draft_orders',
        'read_files',
        'write_files',
        'read_fulfillments',
        'write_fulfillments',
        'read_inventory',
        'write_inventory',
        'read_locations',
        'read_metaobject_definitions',
        'write_metaobject_definitions',
        'read_metaobjects',
        'write_metaobjects',
        'read_merchant_managed_fulfillment_orders',
        'write_merchant_managed_fulfillment_orders',
        'read_orders',
        'write_orders',
        'read_price_rules',
        'write_price_rules',
        'read_products',
        'write_products',
        'read_product_listings',
        'read_reports',
        'write_reports',
        'read_script_tags',
        'write_script_tags',
        'read_shipping',
        'read_themes',
        'return_orders',
        'read_returns',
        'read_marketplace_orders',
        'write_shipping',
        'read_shopify_payments_disputes',
        'read_returns',
        'write_returns',
        'read_third_party_fulfillment_orders',
        'write_third_party_fulfillment_orders'
    ]
];